### ISSUE TITLE
Use autopilotpattern/vault in other projects

### ISSUE THREAD

**Issue by leoj3n** [autopilotpattern/vault#4]
If it weren't for the setup script and all the local files it depends on, it seems like it would be reasonable to include autopilotpattern/vault as a service image in a compose file.

Something like `local-compose.yml`:

```yml
version: "3.4"

services:

  consul:
    image: autopilotpattern/vault:latest
    ports:
      - "8500"
    environment:
      - CONSUL=consul
      - CONSUL_DATACENTER_NAME=dc1

  mongo:
    depends_on:
      - consul
    build:
      context: ./mongo

  node:
    depends_on:
      - mongo
    build:
      context: ./node
    ports:
      - "3030:3030"
      - "8012:8012"
```

However this is insufficient because all of the files the `setup.sh` script relies on, and the setup script itself, are artifacts local to this repository and not included in the docker build artifact.

Can we think of a way to make the setup script (and supporting files) work differently so that it makes sense to use the vault image as outlined above?

I think one alternative is to manually copy the setup script and relied upon files to the project including the vault image, but the main problem with this is as the vault repo evolves, changes to those files that were manually copied over will not be pulled in automatically.

Another alternative would be to fork this autopilotpattern/vault repo and add in the new stuff for our project, but that seems like it would lead to merge conflicts and such.

It would be nice if you could drop this image into an existing setup and get the basic demo working without having to essentially merge two projects files (seems to somewhat eliminate the usefulness of using the built image directly).

However, that might not be practical, and the practical advice might be to just take the autopilotpattern/vault repo in whatever state you find it and use it as a template, while manually checking back for any updates or improvements to the setup script or otherwise that you want to pull in to your copy.

Anyways, would like someones thoughts on this so I can submit a PR to the README to clarify the recommended way of using this repo or image, depending.

**Comment by leoj3n** [comment]
Perhaps from a security standpoint, decoupling the app code entirely from the consul+vault repo is a benefit... Assuming the separate `docker-compose` projects can communicate over the local docker host during local development, but I'm not sure if this is possible; need to do some research.

**Comment by leoj3n** [comment]
## Update

There seems to be three ways of getting vault (plus consul) into another docker-compose project.

### `network:`

The two separately-spun-up projects are able to communicate over the local docker network using this configuration in the `local-compose.yml` of the project containing the app code:

```yml
version: "3.7"

# Use existing network instead of the service if already running consul-vault
# separately beforehand.
networks:
  default:
    external:
      name: consul-vault_default
```

The name of the other project is `consul-vault` thus the network is called `consul-vault_default` thanks to docker's standardized naming conventions for container instances.

You might also save this as `net-compose.yml` and compose a docker command like:

```console
$ docker-compose --project-name 'myapp' --file 'local-compose.yml' --file 'net-compose.yml' up --detach
```

If your development process would be aided by persisting consul and vault data to a backend locally, or if you are wanting to test out consul+vault clustering locally, or perhaps (if for some reason) your app needs to connect to consul and vault over TLS when locally under development, then consider use the `networks:` method. However, the `IS_DEV=1` method might be better.

### `IS_DEV=1`

It's also possible to pull in an image that simply spins up vault and consul in their zero-setup-required but also no-data-preserved `-dev` modes (notice the `IS_DEV=1`):

```yml
version: "3.7"

services:

  consul-vault:
    image: "${CONSUL_VAULT_LATEST}"
    ports:
      - "8200:8200"
      - "8500:8500"
    environment:
      - IS_DEV=1

  mongo:
    depends_on:
      - consul-vault
```

You might also save this as `image-compose.yml` and compose a docker command like:

```console
$ docker-compose --project-name 'myapp' --file 'local-compose.yml' --file 'image-compose.yml' up --detach
```

If you need a simple, single-instance dev setup for your app to connect to for development purposes, then it is probably more lightweight to use the image method with `IS_DEV=1` in your `local-compose.yml`. This also might have the benefit of a clean consul and vault database every time you start your app cluster, which makes your app development process more reproducible.

### `--file`

A final way you could bring consul-vault in `-dev` mode into another docker project with app code is by cloning consul-vault and specifying `--file` locations to `local-compose.yml` and `dev-compose.yml` in consul-vault which might look like:

```console
$ docker-compose --project-name 'myapp' --file 'local-compose.yml' --file '../consul-vault/yml/local-compose.yml' --file '../consul-vault/yml/dev-compose.yml' up --detach
```

**Comment by leoj3n** [comment]
It's also possible to pull in an image that simply spins up vault and consul in their zero-setup-required but also no-data-preserved `-dev` modes (notice the `IS_DEV=1`):

```yml
version: "3.7"

services:

  consul-vault:
    image: "${CONSUL_VAULT_LATEST}"
    ports:
      - "8200:8200"
      - "8500:8500"
    environment:
      - IS_DEV=1

  mongo:
    depends_on:
      - consul-vault
```

If you need a simple, single-instance dev setup for your app to connect to for development purposes, then use the image method with `IS_DEV=1` in your `local-compose.yml`.

However, if your development process be aided by persisting consul and vault data to a backend locally, or if you are wanting to test out the clustering capabilities locally, use the `networks:` method.
